### ISSUE TITLE
Are you trying to make the missing item's textures?

### ISSUE THREAD

**Issue by SofiaRedmond** [xMikux/Slimefun-Resourcepack#4]
**I have a  project what uses this resource pack (item-models.yml too) and i find missing items, i want to ask if i can help you to complete the missing items textures, making the items  textures at my own and sharing it with you.**

**I would just need a little coordination with you.**

 **(Or if you are working in that whit another person, just say it to me and i will wait for the next release of this resource.)**

---
### I was forced to put the "?" icons because they didn't exist on the resource pack. (and because magenta and black squares looks horrible.)
![5118693263065328066_121](https://user-images.githubusercontent.com/86848962/164445382-0714723f-dd51-41ec-8c89-8486fba31d08.jpg)
---

**Comment by xMikux** [comment]
Hi, thanks for help!
To add the the item texture, need to edit the item to https://github.com/xMikux/Slimefun-Resourcepack/blob/main/Resourcepack/items_packs/slimefun/textures.yml and add same path of the model.json
on your image, look like is on energy category, so the texture png should put on the ``Resourcepack/resource_pack/assets/slimefun/textures/slimefun/energy/``
and add the model json to ``Resourcepack/resource_pack/assets/slimefun/models/slimefun/energy/``
I know this is little confusing, because I using the IA (a plugin) to generate this.
Feel free to add me friend on Discord Efina#0877
